### ISSUE TITLE
The model does not work as expected? And I can not find the reason for bad predictions.

### ISSUE THREAD

**Issue by halophy** [vinspdb/ImagePPMiner#2]
When I run the main.py file directly using the prompt command, I get a bad predictions like shown in the picture. Could you please provide a better parameter setting for the current model? And the same problem also emerges in the project [PREMIERE](https://github.com/vinspdb/PREMIERE).

python main.py -event_log helpdesk -n_layers 2
![image](https://github.com/vinspdb/ImagePPMiner/assets/52266584/85c94696-76a7-4b6e-bef0-f39bf9af428e)

**Comment by vinspdb** [comment]
Dear @halophy,
I have re-run the code on my machine with the Helpdesk log, and the model works correctly.
I have attached the screen to you.
I cannot reproduce your error.
![screen](https://github.com/vinspdb/ImagePPMiner/assets/57073656/09f142f6-6515-425a-ae74-a36c31217936)
I am using:
Tensorflow 2.10.0
pm4py 2.2.30 
scikit_learn 1.1.3

**Comment by vinspdb** [comment]
I also tried the dataset receipt on PREMIERE, and the model works correctly.
